version: '3'

services:
  fastapi:
    build:
      context: fastapi
      dockerfile: Dockerfile
    container_name: fastapi
    environment:
      TZ: Europe/Madrid
    ports:
      - 8000:8000
    networks:
      - monitoring_network

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      TZ: Europe/Madrid
    ports:
      - 1880:1880
    volumes:
      - ./node_red/data:/data
    networks:
      - monitoring_network
    depends_on:
      - fastapi

  mage:
    command: mage start ${PROJECT_NAME}
    build:
      context: mage
      dockerfile: Dockerfile
    container_name: mage
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      REQUIRE_USER_AUTHENTICATION: "1"
      TZ: Europe/Madrid
    ports:
      - 6789:6789
    volumes:
      - ./mage:/home/src/
    restart: on-failure:5
    networks:
      - monitoring_network
    depends_on:
      - fastapi

networks:
  monitoring_network:
