{
 "title": "Productos",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "SELECT distinct hostname\nFROM \"products\"\n WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
   },
   {
    "name": "name",
    "query": "SELECT distinct name\nFROM \"products\"\nWHERE \n\"time\" >= $__timeFrom AND \"time\" <= $__timeTo and \nhostname == '$hostname'"
   }
  ]
 },
 "panels": [
  {
   "title": "Precio $name",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"price\", \"time\" FROM \"products\"  WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND (\"name\" = '$name' AND \"hostname\" = '$hostname') ORDER BY \"time\" DESC"
    }
   ]
  },
  {
   "title": "Ultimos valores del producto",
   "type": "stat",
   "gridPos": { "h": 13, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"price\", \"rating\", \"reviews\", \"name\", \"url\" FROM \"products\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND (\"name\" = '$name' AND \"hostname\" = '$hostname') ORDER BY \"time\" DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Maximos",
   "type": "stat",
   "gridPos": { "h": 13, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT  max(price) as price, max(rating) as rating, max(reviews) as reviews\r\nFROM \"products\" \r\nWHERE \r\n\"time\" >= $__timeFrom \r\nAND \"time\" <= $__timeTo \r\nAND (\"name\" = '$name' \r\nAND \"hostname\" = '$hostname')\r\nAND (\"price\" IS NOT NULL)\r\nAND (\"rating\" IS NOT NULL)\r\nAND (\"reviews\" IS NOT NULL)"
    }
   ]
  },
  {
   "title": "Mínimos",
   "type": "stat",
   "gridPos": { "h": 13, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT min(price) as price, min(rating) as rating, min(reviews) as reviews\r\nFROM \"products\" \r\nWHERE \r\n\"time\" >= $__timeFrom \r\nAND \"time\" <= $__timeTo \r\nAND (\"name\" = '$name' \r\nAND \"hostname\" = '$hostname')\r\nAND (\"price\" IS NOT NULL)\r\nAND (\"rating\" IS NOT NULL)\r\nAND (\"reviews\" IS NOT NULL)"
    }
   ]
  },
  {
   "title": "Rating $name",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"time\", \"rating\" FROM \"products\"  WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND (\"name\" = '$name' AND \"hostname\" = '$hostname') ORDER BY \"time\" DESC"
    }
   ]
  },
  {
   "title": "Reviews $name",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"reviews\", \"time\" FROM \"products\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND (\"name\" = '$name' AND \"hostname\" = '$hostname') ORDER BY \"time\" DESC"
    }
   ]
  }
 ]
}